### ISSUE TITLE
[enhancement]  Forum - Line Breaks/ Paragraphs 

### ISSUE THREAD

**Issue by shahbazubair** [MahmoudAlSofyani/dvu-frontend#35]
Ability to accept line breaks or paragraphs for forum rather than having unformatted text block.
<img width="437" alt="Screen Shot 2021-05-19 at 12 08 01 PM" src="https://user-images.githubusercontent.com/6678905/118778525-3abf7680-b89b-11eb-896c-c220efb7397f.png">

**Comment by mahmoudalsof** [comment]
Fixed with PR#37
